### ISSUE TITLE
Discretization of linear state-space models

### ISSUE THREAD

**Issue by mgrutten** [sebdi/kalman-filter.com#1]
In your discussion of discretization of continuous-time models, it would be a nice addition to include discretisation of the process noise as well?

You can do that neatly (for an LTI system) using matrix faction decomposition.  See for example, [Simo Särkkä and Arno Solin, Applied Stochastic Differential Equations, Cambridge University Press, 2019](https://users.aalto.fi/~ssarkka/pub/sde_book.pdf).

Example matlab can be found at [Sarkka/Solin's EKF/UKF toolbox](https://github.com/EEA-sensors/ekfukf/blob/develop/lti_disc.m) or at the [Tracker Component Library](https://github.com/USNavalResearchLaboratory/TrackerComponentLibrary/blob/master/Dynamic_Models/linDynMod2Disc.m).

**Comment by sebdi** [comment]
Thank you for this interesting and valuable reference!

I have added this to the page https://kalman-filter.com/discretization-of-linear-state-space-model/
